<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_mohd331122</name>
   <tag></tag>
   <elementGuidId>975d64ba-4d39-4597-ae68-a2bf009957cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_0_-content-users']/div/div[2]/div/div/table/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;mohd331122&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5b70f6fc-ee98-47a1-80c3-50bbda26d327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 font-medium</value>
      <webElementGuid>ab8ea46d-c809-403a-9166-086b51e80628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mohd331122</value>
      <webElementGuid>9c7a5a4d-ee03-4b39-b009-519f6ee9beb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_0_-content-users&quot;)/div[@class=&quot;rounded-lg border bg-card text-card-foreground shadow-sm mt-8&quot;]/div[@class=&quot;p-6 pt-0&quot;]/div[@class=&quot;rounded-md border&quot;]/div[@class=&quot;relative w-full overflow-auto&quot;]/table[@class=&quot;w-full caption-bottom text-sm&quot;]/tbody[@class=&quot;[&amp;_tr:last-child]:border-0&quot;]/tr[@class=&quot;border-b transition-colors data-[state=selected]:bg-muted cursor-pointer hover:bg-muted/50&quot;]/td[@class=&quot;p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 font-medium&quot;]</value>
      <webElementGuid>a1f16c66-26a6-4ccb-bc57-34eedf2fee3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_0_-content-users']/div/div[2]/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>1171201d-9216-4c45-a38b-664c69d9052b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::td[2]</value>
      <webElementGuid>15a0489e-07df-4bc5-aa94-46667610c121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::td[2]</value>
      <webElementGuid>440dd6f0-5ef7-4462-9bc3-3d34d547008f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test1@email.com'])[1]/preceding::td[1]</value>
      <webElementGuid>c50298f1-0bb2-4083-8a03-8a15149d4f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='student'])[1]/preceding::td[2]</value>
      <webElementGuid>95596239-155d-4deb-bb19-e546fd817df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mohd331122']/parent::*</value>
      <webElementGuid>37bfb01a-6868-48f6-8b6e-654c9359fb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>80dd3866-fc9d-4f76-a3a4-4f50b8c2aa5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'mohd331122' or . = 'mohd331122')]</value>
      <webElementGuid>b42c1bb6-20c2-4a7f-aaf1-43fd84dcad95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
