<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_mohd33112</name>
   <tag></tag>
   <elementGuidId>34966bc0-ace0-4485-aca9-8e67797323aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_0_-content-audit']/div/div[2]/div/table/tbody/tr[100]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(100) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a0692e80-6570-4e6c-8495-67f4006bcfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 font-medium</value>
      <webElementGuid>dff905e3-e718-4707-8796-8d8118837886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mohd33112</value>
      <webElementGuid>f8399ceb-60d7-4fa2-bc18-c30d6d8ad40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_0_-content-audit&quot;)/div[@class=&quot;rounded-lg border text-card-foreground shadow-sm border-border/50 bg-card overflow-hidden&quot;]/div[@class=&quot;overflow-x-auto&quot;]/div[@class=&quot;relative w-full overflow-auto&quot;]/table[@class=&quot;w-full caption-bottom text-sm&quot;]/tbody[@class=&quot;[&amp;_tr:last-child]:border-0&quot;]/tr[@class=&quot;border-b data-[state=selected]:bg-muted hover:bg-muted/20 transition-colors&quot;]/td[@class=&quot;p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 font-medium&quot;]</value>
      <webElementGuid>0eebe907-2c9b-48a3-ae7c-c14669172a4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_0_-content-audit']/div/div[2]/div/table/tbody/tr[100]/td</value>
      <webElementGuid>f2f9175f-9566-4f44-bc3e-bc5e71e904a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Successful login'])[85]/following::td[3]</value>
      <webElementGuid>b99c1eef-1a84-480c-a47b-e71bba79bb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUCCESS'])[85]/following::td[4]</value>
      <webElementGuid>8df508c7-0277-4680-88ab-148c64089940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='::1'])[100]/preceding::td[1]</value>
      <webElementGuid>9b474f59-3fe1-4b76-9469-e9199cd54fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUCCESS'])[86]/preceding::td[2]</value>
      <webElementGuid>6b967d77-698b-449d-9c10-ba05fd1f8fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[100]/td</value>
      <webElementGuid>0b6a7262-3b84-47f7-9a12-765367d998b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'mohd33112' or . = 'mohd33112')]</value>
      <webElementGuid>01ff4f80-7868-4095-8181-d0282851c423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
