<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fl-ids-deployment-7696675586-6pqc714202_6bcc94</name>
   <tag></tag>
   <elementGuidId>113fd339-92d0-41a4-84fd-eec91fd5b3b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_0_-content-health']/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.justify-between.items-start.mb-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AMREADY&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>910f56ea-66f2-4ef2-99bb-b053426f2798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-start mb-4</value>
      <webElementGuid>ab762208-7d60-4f15-929b-12b9f952cd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AMREADY</value>
      <webElementGuid>f8fa9ec9-8910-4b8d-8316-6d17b0b32931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_0_-content-health&quot;)/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6&quot;]/div[@class=&quot;rounded-lg border text-card-foreground shadow-sm bg-card border-border/50 overflow-hidden hover:border-primary/30 transition-all group cursor-pointer ring-1 ring-primary/20&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;flex justify-between items-start mb-4&quot;]</value>
      <webElementGuid>8836ae77-75bd-4b38-b689-737eea6abd85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_0_-content-health']/div[2]/div/div/div</value>
      <webElementGuid>7bb668be-f216-4b91-aad7-ddd9cc14bdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div</value>
      <webElementGuid>1ba98ea7-ee29-418b-bc47-c8b640748a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AMREADY' or . = 'fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AMREADY')]</value>
      <webElementGuid>16bfa1a6-884a-493d-8e72-17b7bff6aed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
