<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fl-ids-deployment-7696675586-6pqc714202_47c944</name>
   <tag></tag>
   <elementGuidId>5a231c4a-3896-4f93-892e-aee4dab1674a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-_r_0_-content-health']/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.gap-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AM$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ecc3f32-6d1f-457d-a0b5-e7ca06a08ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-3</value>
      <webElementGuid>f7488a75-f381-4240-976a-efccb3c84c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AM</value>
      <webElementGuid>a4d25cd3-a6c9-43fe-9b38-6ca3a41c04b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_0_-content-health&quot;)/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6&quot;]/div[@class=&quot;rounded-lg border text-card-foreground shadow-sm bg-card border-border/50 overflow-hidden hover:border-primary/30 transition-all group cursor-pointer&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;flex justify-between items-start mb-4&quot;]/div[@class=&quot;flex items-center gap-3&quot;]</value>
      <webElementGuid>82f9c65f-a893-4b12-8350-b29c1b2960b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_0_-content-health']/div[2]/div/div/div/div</value>
      <webElementGuid>55a007dd-1d8d-41dd-a241-bd7e96df3773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='READY'])[1]/preceding::div[3]</value>
      <webElementGuid>c9b865aa-ce1c-423a-aa52-38883522e385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>fe8e9da5-e791-42ab-90b8-18f0efaa89cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AM' or . = 'fl-ids-deployment-7696675586-6pqc71/4/2026, 12:13:40 AM')]</value>
      <webElementGuid>1323927d-b368-4f4a-9a7e-6cee3a7af356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
